2020-07-04 15:38:00,121 ERROR: Exception on / [GET] [in /usr/local/lib/python3.7/dist-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/dist-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/mohamed/Documents/web/flask/microblog/app/routes.py", line 33, in home
    return render_template('index.html', title="Microblog", posts=posts, form=form)
  File "/usr/local/lib/python3.7/dist-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/usr/local/lib/python3.7/dist-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.7/dist-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.7/dist-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.7/dist-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/mohamed/Documents/web/flask/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/mohamed/Documents/web/flask/microblog/app/templates/base.html", line 4, in top-level template code
    {% block head %}
  File "/home/mohamed/Documents/web/flask/microblog/app/templates/base.html", line 13, in block "head"
    {% block style %}
  File "/home/mohamed/Documents/web/flask/microblog/app/templates/base.html", line 14, in block "style"
    <style>{{ bootstrap.load_css() }}</style>
  File "/usr/local/lib/python3.7/dist-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'bootstrap' is undefined
2020-07-04 15:39:07,130 INFO: Microblog startup [in /home/mohamed/Documents/web/flask/microblog/app/__init__.py:52]
2020-07-04 15:40:24,997 INFO: Microblog startup [in /home/mohamed/Documents/web/flask/microblog/app/__init__.py:52]
2020-07-05 09:38:54,279 INFO: Microblog startup [in /home/mohamed/Documents/dev/web_dev/flask/microblog/app/__init__.py:50]
2020-07-05 09:53:56,303 INFO: Microblog startup [in /home/mohamed/Documents/dev/web_dev/flask/microblog/app/__init__.py:50]
2020-07-05 10:03:30,015 INFO: Microblog startup [in /home/mohamed/Documents/dev/web_dev/flask/microblog/app/__init__.py:50]
2020-07-05 10:08:57,261 INFO: Microblog startup [in /home/mohamed/Documents/dev/web_dev/flask/microblog/app/__init__.py:50]
2020-07-05 10:09:02,777 ERROR: Exception on /login [GET] [in /usr/local/lib64/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib64/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mohamed/Documents/dev/web_dev/flask/microblog/app/routes.py", line 54, in login
    return render_template('login.html', form=form)
  File "/usr/local/lib64/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/usr/local/lib64/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/mohamed/Documents/dev/web_dev/flask/microblog/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/mohamed/Documents/dev/web_dev/flask/microblog/app/templates/base.html", line 35, in top-level template code
    {% block contents %}
  File "/home/mohamed/Documents/dev/web_dev/flask/microblog/app/templates/login.html", line 27, in block "contents"
    {{ form.submit()(class_="required") }}
TypeError: 'Markup' object is not callable
2020-07-05 10:09:23,251 INFO: Microblog startup [in /home/mohamed/Documents/dev/web_dev/flask/microblog/app/__init__.py:50]
2020-07-05 10:09:26,626 ERROR: Exception on /login [GET] [in /usr/local/lib64/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib64/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mohamed/Documents/dev/web_dev/flask/microblog/app/routes.py", line 54, in login
    return render_template('login.html', form=form)
  File "/usr/local/lib64/python3.7/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.7/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/mohamed/Documents/dev/web_dev/flask/microblog/app/templates/login.html", line 27, in template
    {{ form.submit(class_="required")()( }}
jinja2.exceptions.TemplateSyntaxError: unexpected '}', expected ')'
2020-07-05 10:09:35,951 INFO: Microblog startup [in /home/mohamed/Documents/dev/web_dev/flask/microblog/app/__init__.py:50]
